### ISSUE TITLE
Ei loobi edasi

### ISSUE THREAD

**Issue by RRisto** [RRisto/ettvotted#5]
Kui avada fail ning leida koht, kus kohast alates pole goekodeeringut (alguskoht=len(data["viitepunkt_y"])-data["viitepunkt_y"].isnull().sum()), siis ei loobi edasi, geokodeeritud on ainult esimesed 9 rida.

**Comment by KRaudla** [comment]
Mis väljastatakse alguskoha väärtuseks? Et loopima hakata peab alguskoha väärtus olema integer ning saadud väärtus peab olema väiksem, kui sinu range lõpp. range(10,20). Kui alguskoht on 21, siis negatiivne loop ei tööta. Uurin, testin.

**Comment by RRisto** [comment]
kui 9 rida täidetud, siis alustab ilusti 10st. millegipärast ei tahtnud enam üldse kuskile dataframe väärtusi uuendada (sh kui manuaalselt kirjutasin data["viitepunkt_y"][10]="bla").

**Comment by KRaudla** [comment]
data.head() väljastab viitepunkt_y ja x tulbad? (st on kirjutanud faili ja oskab need uuesti välja lugeda).

j = requests.get(url).content.decode("utf-8")
Kas j väärtus tagastatakse?
data["viitepunkt_x"][i]=j.split(",")[0] Kas prindib tulemuse?

Proovi loobi keskel välja printida dataframe (kas tulpa uuendatakse)?

**Comment by RRisto** [comment]
teema maas, dataframe kirjutamisel on vaja vaja kasutada .loc lisandit, nt data.loc[i,"viitepunkt_x"]=j.split(",")[0], mitte data["viitepunkt_x"][i]=j.split(",")[0] 
http://pandas.pydata.org/pandas-docs/version/0.17.0/indexing.html#indexing-label
