### ISSUE TITLE
Can't convert 'float' object to str implicitly

### ISSUE THREAD

**Issue by KRaudla** [RRisto/ettvotted#7]
Enelase 14,Soinaste kÃ¼la, Ãlenurme vald, Tartumaa
Tedre pÃµik 25,Tallinn
Randla 15-1M,Tallinn (Siin tekib error)
Traceback (most recent call last):
  File "C:/Users/kasutaja/Documents/GitHub/ettvotted/maaamet_geocoding.py", line 28, in <module>
    url = "http://inaadress.maaamet.ee/inaadress/gazetteer?address="+data["aadressid"][i]
TypeError: Can't convert 'float' object to str implicitly

**Comment by RRisto** [comment]
mitmes rida see failis on?

**Comment by KRaudla** [comment]
rida 60. Lahendus: url = "http://inaadress.maaamet.ee/inaadress/gazetteer?address="+str(data["aadressid"][i])
